config/routes.rb
Rails.application.routes.draw do
  resources :blinds
  resources :curtains
  resources :products
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'store#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blind.rb
class Blind < ApplicationRecord
    mount_uploader :image, ImageUploader

    serialize :image, JSON
    belongs_to :user, optional: true
end

app/models/curtain.rb
class Curtain < ApplicationRecord
    mount_uploader :image, ImageUploader

    serialize :image, JSON
    belongs_to :user, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader

    serialize :image, JSON
    belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :blinds
  has_many :curtains
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blinds_controller.rb
class BlindsController < ApplicationController
  before_action :set_blind, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /blinds
  # GET /blinds.json
  def index
    @blinds = Blind.all.order("created_at desc")
  end

  # GET /blinds/1
  # GET /blinds/1.json
  def show
  end

  # GET /blinds/new
  def new
    @blind = current_user.blinds.build
  end

  # GET /blinds/1/edit
  def edit
  end

  # POST /blinds
  # POST /blinds.json
  def create
    @blind = current_user.blinds.build(blind_params)

    respond_to do |format|
      if @blind.save
        format.html { redirect_to @blind, notice: 'Blind was successfully created.' }
        format.json { render :show, status: :created, location: @blind }
      else
        format.html { render :new }
        format.json { render json: @blind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blinds/1
  # PATCH/PUT /blinds/1.json
  def update
    respond_to do |format|
      if @blind.update(blind_params)
        format.html { redirect_to @blind, notice: 'Blind was successfully updated.' }
        format.json { render :show, status: :ok, location: @blind }
      else
        format.html { render :edit }
        format.json { render json: @blind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blinds/1
  # DELETE /blinds/1.json
  def destroy
    @blind.destroy
    respond_to do |format|
      format.html { redirect_to blinds_url, notice: 'Blind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blind
      @blind = Blind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blind_params
      params.require(:blind).permit(:name, :description, :price, :image)
    end
end

app/controllers/curtains_controller.rb
class CurtainsController < ApplicationController
  before_action :set_curtain, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /curtains
  # GET /curtains.json
  def index
    @curtains = Curtain.all.order("created_at desc")
  end

  # GET /curtains/1
  # GET /curtains/1.json
  def show
  end

  # GET /curtains/new
  def new
    @curtain = current_user.curtains.build
  end

  # GET /curtains/1/edit
  def edit
  end

  # POST /curtains
  # POST /curtains.json
  def create
    @curtain = current_user.curtains.build(curtain_params)

    respond_to do |format|
      if @curtain.save
        format.html { redirect_to @curtain, notice: 'Curtain was successfully created.' }
        format.json { render :show, status: :created, location: @curtain }
      else
        format.html { render :new }
        format.json { render json: @curtain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curtains/1
  # PATCH/PUT /curtains/1.json
  def update
    respond_to do |format|
      if @curtain.update(curtain_params)
        format.html { redirect_to @curtain, notice: 'Curtain was successfully updated.' }
        format.json { render :show, status: :ok, location: @curtain }
      else
        format.html { render :edit }
        format.json { render json: @curtain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curtains/1
  # DELETE /curtains/1.json
  def destroy
    @curtain.destroy
    respond_to do |format|
      format.html { redirect_to curtains_url, notice: 'Curtain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curtain
      @curtain = Curtain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curtain_params
      params.require(:curtain).permit(:name, :description, :price, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("created_at desc")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blinds_helper.rb
module BlindsHelper
end

app/helpers/curtains_helper.rb
module CurtainsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/blinds/_form.html.erb
<%= simple_form_for @blind, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
  </div>
  <label class="file-label">
  <%= f.input :image, as: :file, input_html: { class:"file-input item-image" }, label: false, wrapper: false %>
    <span class="file-cta">
      <span class="file-icon"><i class="fa fa-upload"></i></span>
      <span class="file-label">Choose a file…</span>
    </span>
</label>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blinds/edit.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<h1>Editing Blind</h1>

<%= render 'form', blind: @blind %>

<%= link_to 'Show', @blind %> |
<%= link_to 'Back', blinds_path %>
</div>

app/views/blinds/index.html.erb
	<section class="intro-section">
		<div class="container text-center">
			<div class="row">
				<div class="col-xl-10 offset-xl-1">
					<h2 class="section-title">Quality blinds</h2>
				</div>
			</div>
		</div>
	</section>
<div class="container-fluid p-md-0 ">
			<div class="row portfolios-area">
          <% @blinds.each do |blind| %>
				<div class="mix col-lg-6 col-md-6 web">
            <%= image_tag(blind.image_url(:default), class: "portfolio-item set-bg") %>
				</div>
			    <%= blind.name %>
      <%= blind.description %>
      <%= blind.price %>
      <%= link_to "Show", blind %>
      <% if user_signed_in? %>
      <%= link_to "Edit", edit_blind_path(blind) %>
      <%= link_to "Destroy", blind, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
          <% end %>
			</div>
		</div>
	</section>
<% if user_signed_in? %>

<%= link_to "New Blind", new_blind_path, class: "site-btn" %>
<% end %>
</div>

app/views/blinds/new.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<h1>New Blind</h1>

<%= render 'form', blind: @blind %>

<%= link_to 'Back', blinds_path %>
</div>

app/views/blinds/show.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<%= image_tag(@blind.image_url(:default)) %>
<p>
  <strong>Name:</strong>
  <%= @blind.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blind.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @blind.price %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_blind_path(@blind) %>
<% end %> |
<%= link_to 'Back', blinds_path %>
</div>

app/views/curtains/_form.html.erb
<%= simple_form_for @curtain, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
  </div>
  <label class="file-label">
  <%= f.input :image, as: :file, input_html: { class:"file-input item-image" }, label: false, wrapper: false %>
    <span class="file-cta">
      <span class="file-icon"><i class="fa fa-upload"></i></span>
      <span class="file-label">Choose a file…</span>
    </span>
</label>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/curtains/edit.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<h1>Editing Curtain</h1>

<%= render 'form', curtain: @curtain %>

<%= link_to 'Show', @curtain %> |
<%= link_to 'Back', curtains_path %>
</div>

app/views/curtains/index.html.erb
		<section class="intro-section">
		<div class="container text-center">
			<div class="row">
				<div class="col-xl-10 offset-xl-1">
					<h2 class="section-title">Quality curtains</h2>
				</div>
			</div>
		</div>
	</section>
    <div class="container-fluid p-md-0 ">
			<div class="row portfolios-area">
          <% @curtains.each do |curtain| %>
				<div class="mix col-lg-6 col-md-6 web">
            <%= image_tag(curtain.image_url(:default), class: "portfolio-item set-bg") %>
				</div>
			    <%= curtain.name %>
      <%= curtain.description %>
      <%= curtain.price %>
      <%= link_to "Show", curtain %>
      <% if user_signed_in? %>
      <%= link_to "Edit", edit_curtain_path(curtain) %>
      <%= link_to "Destroy", curtain, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
          <% end %>
			</div>
		</div>
	</section>
<% if user_signed_in? %>

<%= link_to "New Curtain", new_curtain_path, class: "site-btn" %>

<% end %>
</div>

app/views/curtains/new.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<h1>New Curtain</h1>

<%= render 'form', curtain: @curtain %>

<%= link_to 'Back', curtains_path %>
</div>

app/views/curtains/show.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<%= image_tag(@curtain.image_url(:default)) %>

<p>
  <strong>Name:</strong>
  <%= @curtain.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @curtain.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @curtain.price %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_curtain_path(@curtain) %>
<% end %> |
<%= link_to 'Back', curtains_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curtainrods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag href = "https://www.w3schools.com/w3css/4/w3.css" %>
    <%= stylesheet_link_tag href = "https://fonts.googleapis.com/css?family=Poppins" %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <%= link_to "Curtainrodssolutions", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
        <%= link_to "Home", root_path, :class => "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Rods", "/products", :class => "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Blinds", "/blinds", :class => "nav-link" %> 
        </li>
        <li class="nav-item">
         <%= link_to "Curtains", "/curtains", :class => "nav-link" %> 
        </li>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  <!-- footer section start -->
	<footer class="footer-section text-center">
		<div class="container">
			<h2 class="section-title mb-5">Contact Us</h2>
			<a href="" class="site-btn">Get in touch</a>
			<div class="social-links">
				<a href=""><span class="fa fa-pinterest"></span></a>
				<a href=""><span class="fa fa-linkedin"></span></a>
				<a href=""><span class="fa fa-instagram"></span></a>
				<a href=""><span class="fa fa-facebook"></span></a>
				<a href=""><span class="fa fa-twitter"></span></a>
			</div>
			<div class="copyright">
    Copyright &copy; 2020 All rights reserved | Curtainrodssolutions
</div>
		</div>
	</footer>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-group">
    <%= f.input :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.input :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.input :price, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.input :image, as: :file, input_html: { class: "form-control-file" }, label: false, wrapper: false %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
	<section class="intro-section">
		<div class="container text-center">
			<div class="row">
				<div class="col-xl-10 offset-xl-1">
					<h2 class="section-title">Quality curtain rods</h2>
				</div>
			</div>
		</div>
	</section>
<section class="portfolio-section">
                     
		<div class="container-fluid p-md-0 ">
			<div class="row portfolios-area">
          <% @products.each do |product| %>
				<div class="mix col-lg-6 col-md-6 web">
            <%= image_tag(product.image_url(:default), class: "portfolio-item set-bg") %>
				      <% if user_signed_in? %>
      <%= link_to "Edit", edit_product_path(product) %>
      <%= link_to "Destroy", product, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
                </div>
	

          <% end %>
			</div>
		</div>
	</section>
<% if user_signed_in? %>
<%= link_to "Enter new curtain rod", new_product_path, class: "site-btn" %>
<% end %>
</div>

app/views/products/new.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">

<%= image_tag(@product.image_url(:default)) %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_product_path(@product) %> 
<% end %> |
<%= link_to 'Back', products_path %>
</div>